core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ngict.urls')),
    path('', include('instructors.urls')),
]

instructors/urls.py
from django.urls import path
from instructors.views import *
from ngict.views import home
from django.conf import settings
from django.conf.urls.static import static



app_name = 'instructors'

urlpatterns = [
    path('', home, name="home"),
    path('instructor_dashboard/', instructor_dashboard, name='instructor_dashboard'),
    path('create_course/', create_course, name='create_course'),
    path('course/<slug:slug>/', course_detail, name='course_detail'),
    path('create_module/', create_modules, name='create_module'),
    path('create_lesson/', create_lesson, name='create_lesson'),
    path('lesson/<int:lesson_id>/upload_resource/', upload_resource, name='upload_resource'),

    path('lesson/<int:lesson_id>/create_assessment/', create_assessment, name='create_assessment'),
    path('create_assessment/', create_assessment, name='create_assessment'),

    path('get_modules_and_lessons/', get_modules_and_lessons, name='get_modules_and_lessons'),

    path('edit_course/<slug:slug>/', edit_course, name='edit_course'),
    path('delete_course/<slug:slug>/', delete_course, name='delete_course'),

    path('save_lesson_data/', save_lesson_data, name='save_lesson_data'),
    path('load_lesson_data/', load_lesson_data, name='load_lesson_data'),

    path('upload_question_answer/', upload_question_answer, name='upload_question_answer'),

    path('save_question_answer_ajax/', save_question_answer_ajax, name='save_question_answer_ajax'),


    path('assessment-list/', assessment_list, name='assessment_list'),
    path('take_assessment/<int:assessment_id>/', take_assessment, name='take_assessment'),
    path('courses/', courses_by_category, name='courses_by_category'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ngict/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import *
from instructors.views import instructor_dashboard

app_name = 'academy'

urlpatterns = [
   
    path('', home, name="home"),
    path('accounts/login/', register_and_login, name='register_and_login'),
    path('signout/', signout, name='signout'),
    path('dashboard/', user_dashboard, name='user_dashboard'),
    path('create_profile/', update_profile, name='update_profile'),
    
    path('instructor_dashboard/', instructor_dashboard, name='instructor_dashboard'),

    path('html_css/', html_css, name='html_css'),

    
    path('enroll/<slug:slug>/', enroll_course, name='enroll_course'),
    path('unenroll/<slug:slug>/', unenroll_course, name='unenroll_course'),

    path('course/<slug:slug>/', course_detail, name='course_detail'),


    path('save_user_codes/', save_user_codes, name='save_user_codes'),
    path('get_user_codes/', get_user_codes, name='get_user_codes'),


    path('projects/', projects, name='projects'),

    path('notes/', notes, name='make_notes'),
    path('ide/', ide, name='ide'),

    path('image-list/', image_list, name='image_list'),
    path('image/<int:image_id>/', view_image, name='view_image'),

    path('get-course-progress/<int:course_id>/', get_course_progress, name='get_course_progress'),

    # URL pattern for marking a lesson as completed
    path('mark-lesson-completed/', mark_lesson_completed, name='mark_lesson_completed'),
    path('connected_visitors/', connected_visitors, name='connected_visitors'),

] 

urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Boxicons CSS -->
    <link rel="stylesheet" href="style.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github-dark.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/monaco-editor@0.4.0/min/vs/editor/editor.main.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.24.0/min/vs/loader.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link rel="shortcut icon" href="https://img.icons8.com/?size=1x&id=dxoYK8bxqiJr&format=png" type="image/x-icon">
    <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>



   
    <title>Nuel-Green ICT</title>
</head>
{% block style %}<style>
    .container {
  display: flex;
  flex-direction: row;
}

.sidebar {
  width: 250px;
  background-color: #333;
  color: #fff;
  padding: 20px;
}

.logo-details {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.logo-details i {
  margin-right: 10px;
}

.nav-links {
  list-style: none;
  padding: 0;
  margin: 0;
}

.nav-links a {
  display: block;
  color: #fff;
  text-decoration: none;
  padding: 10px 0;
  transition: all 0.3s ease;
}

.nav-links a:hover {
  background-color: #555;
  padding-left: 10px;
}

.has-submenu ul {
  list-style: none;
  margin-left: 20px;
  display: none;
}

.has-submenu:hover ul {
  display: block;
}

.profile-details {
  margin-top: auto;
  display: flex;
  align-items: center;
}

.profile-details .user-buttons {
  margin-right: 10px;
}

.profile-details a {
  color: #fff;
  text-decoration: none;
}

.home-section {
  flex: 1;
  padding: 20px;
  background-color: #f5f5f5;
}

/* Add your media queries for responsiveness */

</style>{% endblock style %}

<body>
    <div class="sidebar ">
        <div class="logo-details">
            <i class='bx bxs-alarm'></i>
            <span class="logo-name"><a href="{% url 'academy:home' %}">Nuel-green ICT</a></span>
        </div>
        <ul class="nav-links">
            <li>
                <a href="#">
                    <a href="{% url 'academy:user_dashboard' %}"><i class='bx bx-grid-alt'></i>
                        <span class="link-name">Dashboard</span></a>
                </a>
            </li>

            <li>
                <div class="icon-link">
                    <a href="#">
                        <i class='bx bx-code-alt'></i>
                        <span class="link-name">Front-End Development</span>
                    </a>
                    <i class='bx bxs-chevron-down arrow'></i>
                </div>
                <ul class="sub-menu">
                    <!-- <li><a class="link-name" href="">HTML/CSS</a></li> -->
                    <li><a href="{% url 'academy:html_css' %}">HTML/CSS</a></li>
                    <li><a href="">JavaScript Algorithm</a></li>
                    <li><a href="">Front-End Libraries</a></li>
                </ul>
            </li>

            <li>
                <div class="icon-link">
                    <a href="#">
                        <i class='bx bx-code-alt'></i>
                        <span class="link-name">Data</span>
                    </a>
                    <i class='bx bxs-chevron-down arrow'></i>
                </div>
                <ul class="sub-menu">
                    <!-- <li><a class="link-name" href="">HTML/CSS</a></li> -->
                    <li><a href="">Data Science</a></li>
                    <li><a href="">Data Analytics</a></li>
                    <li><a href="">ML</a></li>
                    <li><a href="">Data Visualization</a></li>
                </ul>
            </li>

            <li>
                <a href="#">
                    <i class='bx bxl-python'></i>
                    <span class="link-name">Python</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class='bx bxl-python'></i>
                    <span class="link-name">Java</span>
                </a>
            </li>

            <li>
                <div class="icon-link">
                    <a href="#">
                        <i class='bx bxs-server'></i>
                        <span class="link-name">Back-End Development & API</span>
                    </a>
                    <i class='bx bxs-chevron-down arrow'></i>
                </div>
                <ul class="sub-menu">
                    <li><a class="link-name" href="">Using Native JavaScript</a></li>
                    <li><a href="">NodeJs</a></li>
                    <li><a href="">NestJs</a></li>
                    <li><a href="">Express.Js</a></li>
                    <li><a href="">Koa.Js</a></li>

                </ul>
                <ul class="sub-menu">
                    <li><a class="link-name" href="">Using Python</a></li>
                    <li><a href="">Django</a></li>
                    <li><a href="">Flask</a></li>
                    <li><a href="">Pyramid</a></li>
                    <li><a href="">Bottle</a></li>
                    <li><a href="">CherryPy</a></li>
                    <li><a href="">Tonado</a></li>
                </ul>
            </li>
            <!-- <li>
                <a href="#">
                    <i class='bx bx-task'></i>
                    <span class="link-name">Category</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class='bx bx-signal-5'></i>
                    <span class="link-name">Category</span>
                </a>
            </li> -->
            <!-- <li>
                <a href="#">
                    <i class='bx bx-signal-5'></i>
                    <span class="link-name">Category</span>
                </a>
            </li> -->
            <li>
                <div class="icon-link">
                    <a href="#">
                        <i class='bx bx-book-alt'></i>
                        <span class="link-name">Databases</span>
                    </a>
                    <i class='bx bxs-chevron-down arrow'></i>
                </div>
                <ul class="sub-menu">
                    <li><a class="link-name" href="">Relational Databases</a></li>
                    <li><a href="">MySQL</a></li>
                    <li><a href="">PostgreSQL</a></li>
                    <li><a href="">Oracle Databases</a></li>
                    <li><a href="">Microsoft SQL sever</a></li>
                    <li><a href="">SQLite</a></li>
                    <li><a href="">IBM DB2</a></li>
                    <li><a href="">MariaDB</a></li>
                    <li><a href="">Google Cloud SQL</a></li>
                    <li><a href="">Azure SQL database</a></li>
                    <li><a href="">Amazon RDS</a></li>
                </ul>

                <ul class="sub-menu">
                    <li><a class="link-name" href="">Non-Relational Databases</a></li>
                    <li><a href="">MongoDB</a></li>
                    <li><a href="">Cassandra</a></li>
                    <li><a href="">CouchDB</a></li>
                    <li><a href="">Redis</a></li>
                    <li><a href="">Neo4j(graph database)</a></li>
                    <li><a href="">Amazon DynamoDB</a></li>
                    <li><a href="">Google Cloud Firestore</a></li>
                    <li><a href="">Apache Hbase</a></li>
                </ul>
            </li>
        </ul>
        <li>
            
            <div class="profile-details">
                <div class="user-buttons">
                    {% if user.is_authenticated %}
                        <a class="btn btn-primary" href="{% url 'academy:signout' %}"><i class='bx bx-log-out-circle'></i></a>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'academy:signin' %}">Signin</a>
                        <a class="btn btn-primary" href="{% url 'academy:signup' %}">signup</a>
                    {% endif %}
                    
                </div>
                <div class="profile-content">
                    <a href="{% url 'academy:update_profile' %}"><img src="https://www.clipartmax.com/png/middle/190-1904735_bokbokstars-121-classic-stock-icons-manager-icon-3d.png"
                        alt=""></a>
                </div>
                
            </div>
            
        </li>
    </div>

    <section class="home-section">
        <div class="home-content">
            <i class='bx bx-menu'></i>
            <span class="text"></span>
        </div>

        {% comment %} {% block home %}{% endblock home %} {% endcomment %}
        {% block html_css %}{% endblock html_css %}
        {% block signin %}{% endblock signin %}
        {% block user_profile %}{% endblock user_profile %}
        {% block signup %}{% endblock signup %}
        {% block user_dashboard %}{% endblock user_dashboard %}
        {% block course_list %}{% endblock course_list %}
        {% block content %}{% endblock %}
        {% block projects %}{% endblock projects %}
        
    </section>
    
    

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            console.log("DOM content loaded.");
            const projectForm = document.getElementById("project-form");
            console.log("Project form:", projectForm);
    
            const projectForm = document.getElementById("project-form");
            const projectFeedback = document.getElementById("project-feedback");
            const userDashboardUrl = "{% url 'academy:user_dashboard' %}";
          
            projectForm.addEventListener("submit", async (event) => {
              event.preventDefault();
          
              const formData = new FormData(projectForm);
          
              try {
                const response = await fetch(userDashboardUrl, {
                  method: "POST",
                  body: formData,
                });
          
                if (response.ok) {
                  const data = await response.json();
                  projectFeedback.innerHTML = `Project submitted: <a href="${data.project_link}" target="_blank">${data.project_title}</a>`;
                } else {
                  console.error("Response not OK:", response);
                  projectFeedback.innerHTML = "Project submission failed.";
                }
              } catch (error) {
                console.error("Error occurred:", error);
                projectFeedback.innerHTML = "An error occurred while submitting the project.";
              }
            });
          
          });
    </script>
        
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.27.0/min/vs/loader.js"></script>
    <script src="{% static 'js/ide.js' %}"></script>
    <script>hljs.highlightAll();</script>
    <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

templates/dashboard.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github-dark.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/monaco-editor@0.4.0/min/vs/editor/editor.main.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.24.0/min/vs/loader.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link
      rel="icon"
      href="https://tinypic.host/images/2023/12/16/logo-photoaidcom-cropped.png"
    />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/monaco-editor@0.23.0/min/vs/editor/editor.main.css">

    <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

    <title>Nuel-Green ICT</title>
  </head>

  <body>
    <header class="dashboard-header">
      <nav class="dashboard-nav">
        <div class="logo">
          <a href="{% url 'academy:home' %}">
            <img
              width="80px"
              src="https://tinypic.host/images/2023/09/24/2nd-Nuel-Green-White-Background.png"
              alt="logo"
            />
          </a>
          <a href="{% url 'academy:home' %}">
            <h3>Nuel-Green ICT</h3>
          </a>
        </div>

        <div class="right-nav">
          <div class="notification">
            <a href=""> <i class="bx bxs-envelope"></i></a>
            <a href=""><i class="bx bxs-bell"></i></a>
          </div>

          <div class="user-avatar">
            <a href="">
              <img
                src="https://static.vecteezy.com/system/resources/thumbnails/002/002/403/small/man-with-beard-avatar-character-isolated-icon-free-vector.jpg"
                alt="User Avatar"
                class="user-avatar"
              />
              <p>{{ user.username }}</p>
            </a>
          </div>
        </div>
      </nav>
    </header>

    <section class="dashboard-content">
      <aside class="dashboard-sidebar">
        <div class="sidebar-header">
          <h3>{{ user.username }}'s</h3>
          <a href="{% url 'academy:user_dashboard' %}">
            <i class="bx bxs-dashboard"></i>
            <h4>Dashboard</h4>
          </a>
        </div>
        <ul class="sidebar-menu">
          <li>
            <a href="#" class="active"></a>
          </li>
          <li>
            <i class="bx bxs-book"></i>
            <a href="{% url 'instructors:courses_by_category' %}">Courses</a>
          </li>

          <li>
            <i class="bx bxs-network-chart"></i>
            <a href="{% url 'academy:projects' %}" class="projects-link"
              >Projects</a
            >
          </li>

          <li>
            <a href="{% url 'instructors:assessment_list' %}">Assessments</a>

          </li>

          <li>
            <a href="{% url 'academy:make_notes' %}">Notes</a>

          </li>

          <li>
            <a href="{% url 'academy:ide' %}">Practice</a>

          </li>
          

          <li>
            <i class="bx bxs-envelope"></i>
            <a href="#">Messages</a>
          </li>

          <li>
            <i class="bx bxs-calendar"></i>
            <a href="#">Calendar</a>
          </li>
          <li>
            <i class="bx bxs-cog"></i>
            <a href="#">Settings</a>
          </li>
          <li>
            {% if user.is_staff %}
            <i class="bx bxs-briefcase"></i>
            <a
              href="{% url 'instructors:instructor_dashboard' %}"
              class="btn-primary underlines"
              >Instructor</a
            >
            {% else %}
            <p></p>
            {% endif %}
          </li>
          <li>
            {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'academy:signout' %}"
              ><i class="bx bx-log-out-circle"></i
            ></a>
            {% else %}
            <a class="btn btn-primary" href="{% url 'academy:register_and_login' %}"
              >Signin</a
            >
            <a class="btn btn-primary" href="{% url 'academy:register_and_login' %}"
              >signup</a
            >
            {% endif %}
          </li>
        </ul>
      </aside>

      <main class="dashboard-main">
        {% block content %}{% endblock content %}
      </main>
    </section>

    <script>

        function confirmUnenroll(courseTitle, unenrollUrl) {
            const confirmation = confirm(`Are you sure you want to unenroll from ${courseTitle}?`)
            if (confirmation) {
                window.location.href = unenrollUrl
            }
        }


        // Assuming you have a way to track completed lessons in your data
        const completedLessons = [
            {% for progress in course_progress.user_progress %}
                {% if progress.status == "Completed" %}
                { { progress.week } },
                {% endif %}
            {% endfor %}
        ]; // Example: Lessons marked as "Completed"

        const lessonOverlays = document.querySelectorAll('.lesson-overlay');
        lessonOverlays.forEach((overlay, index) => {
            if (completedLessons.includes(index + 1)) {
                // Calculate the percentage completed
                const percentage = ((index + 1) / lessonOverlays.length) * -100;

                // Update the progress bar width and text
                const progressBar = overlay.querySelector('.lesson-progress-bar');
                const progressText = overlay.querySelector('.lesson-progress-text');

                progressBar.style.width = `${percentage}%`;
                progressText.textContent = `${percentage.toFixed(0)}%`;
            }
        });


        // JavaScript to change the course card colors with time
      function changeCourseCardColors() {
        const courseCards = document.querySelectorAll('.img-overlay');
        const colors = [
            'rgba(255, 0, 0, 0.5)', // Red
            'rgba(0, 0, 255, 0.5)', // Blue
            'rgba(0, 255, 0, 0.5)', // Green
            'rgba(57, 0, 153, 0.5)', //
            'rgba(158, 0, 89, 0.5)', //
            'rgba(255, 84, 0, 0.5)', //
            'rgba(4, 150, 255, 0.5)', //

            // Add more colors as needed
        ];

        let colorIndex = 0;

        setInterval(() => {
            courseCards.forEach((card, index) => {
                const overlay = card.querySelector('.course-overlay');
                overlay.style.background = colors[(colorIndex + index) % colors.length];
            });

            colorIndex = (colorIndex + 1) % colors.length;
        }, 2000); // Change colors every 5 seconds (adjust as needed)
      }

      // Call the function to start changing colors
      changeCourseCardColors();
    </script>

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        console.log("DOM content loaded.");
        const projectForm = document.getElementById("project-form");
        console.log("Project form:", projectForm);

        const projectForm = document.getElementById("project-form");
        const projectFeedback = document.getElementById("project-feedback");
        const userDashboardUrl = "{% url 'academy:user_dashboard' %}";

        projectForm.addEventListener("submit", async (event) => {
          event.preventDefault();

          const formData = new FormData(projectForm);

          try {
            const response = await fetch(userDashboardUrl, {
              method: "POST",
              body: formData,
            });

            if (response.ok) {
              const data = await response.json();
              projectFeedback.innerHTML = `Project submitted: <a href="${data.project_link}" target="_blank">${data.project_title}</a>`;
            } else {
              console.error("Response not OK:", response);
              projectFeedback.innerHTML = "Project submission failed.";
            }
          } catch (error) {
            console.error("Error occurred:", error);
            projectFeedback.innerHTML =
              "An error occurred while submitting the project.";
          }
        });
      });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.27.0/min/vs/loader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.27.0/min/vs/loader.js"></script>
    <script src="{% static 'js/ide.js' %}"></script>

    <script>
      hljs.highlightAll();
    </script>
    <script src="{% static 'js/index.js' %}"></script>
    <style>
      .sidebar-header a {
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
      }

      .sidebar-header a i {
        font-size: 30px;
      }

      .user-avatar a {
        display: flex;
        color: black;
        font-weight: 100;
      }

      .user-avatar img {
        width: 45px;
        height: 45px;
        border-radius: 50%;
        border: none;
        margin-bottom: 10px;
      }
    </style>
  </body>
</html>

templates/ide.html
{% extends "dashboard.html" %}

{% load static %}


{% block content %}
    <style>
        body {
            padding: 2rem 1rem;
        }
        .editor_input, .editor_output {
            width: 520px;
            height: 230%;
            border: 2px solid black;
        }
        .editor_output{
            width: 1550px;
        }
        .code_editor_segments{
            display: flex;
        }
        .code_editor_wrapper {
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }

        .run_btn{
            border:none;
            border-radius:0.5rem;
            outline:none;
            padding:1rem;
            font-size:20px;
            font-weight:900;
            background-color:brown;
        }
        .code{
            margin: 5px;
        }
    </style>
</head>
<body>
   
    <section class="code_editor container">
        <div class="code_editor_container">
            <div class="code_editor_wrapper">
                <div class="code_editor_segments">

                    <div class="code">
                        <h4>HTML</h4>
                        <div class="editorContainer editor_input" id="htmlEditor"></div>
                    </div>

                    <div class="code">
                        <h4>CSS</h4>
                        <div class="editorContainer editor_input" id="cssEditor"></div>
                    </div>

                    <div class="code">
                        <h4>JavaScript</h4>
                        <div class="editorContainer editor_input" id="jsEditor"></div>
                    </div>
                    
                </div>
                <button class="run_btn" id="runButton"><i class='bx bx-play'></i>Run</button>
                <div class="code_editor_segments">
                    <div class="output">
                        <h4>OutPut</h4>
                        <pre class="editor_output" id="output"></pre>
                    </div>
                    
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/visitors.html
<!-- templates/connected_visitors.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connected Visitors</title>
</head>
<body>
    <h1>Connected Visitors</h1>
    <ul>
        {% for visitor in connected_visitors %}
            <li>
                IP Address: {{ visitor.ip_address }}<br>
                Browser: {{ visitor.browser }}<br>
                OS: {{ visitor.os }}<br>
                Device: {{ visitor.device }}<br>
                Time Spent: {{ visitor.time_spent }} seconds<br>
            </li>
        {% endfor %}
    </ul>
</body>
</html>