core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ngict.urls')),
    path('', include('instructors.urls')),
]

instructors/urls.py
from django.urls import path
from instructors.views import *
from ngict.views import home
from django.conf import settings
from django.conf.urls.static import static



app_name = 'instructors'

urlpatterns = [
    path('', home, name="home"),
    path('instructor_dashboard/', instructor_dashboard, name='instructor_dashboard'),
    path('create_course/', create_course, name='create_course'),
    path('course/<slug:slug>/', course_detail, name='course_detail'),
    path('create_module/', create_modules, name='create_module'),
    path('create_lesson/', create_lesson, name='create_lesson'),
    path('lesson/<int:lesson_id>/upload_resource/', upload_resource, name='upload_resource'),

    path('lesson/<int:lesson_id>/create_assessment/', create_assessment, name='create_assessment'),
    path('create_assessment/', create_assessment, name='create_assessment'),

    path('get_modules_and_lessons/', get_modules_and_lessons, name='get_modules_and_lessons'),

    path('edit_course/<slug:slug>/', edit_course, name='edit_course'),
    path('delete_course/<slug:slug>/', delete_course, name='delete_course'),

    path('save_lesson_data/', save_lesson_data, name='save_lesson_data'),
    path('load_lesson_data/', load_lesson_data, name='load_lesson_data'),

    path('upload_question_answer/', upload_question_answer, name='upload_question_answer'),

    path('save_question_answer_ajax/', save_question_answer_ajax, name='save_question_answer_ajax'),


    path('assessment-list/', assessment_list, name='assessment_list'),
    path('take_assessment/<int:assessment_id>/', take_assessment, name='take_assessment'),
    path('courses/', courses_by_category, name='courses_by_category'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ngict/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import *
from instructors.views import instructor_dashboard

app_name = 'academy'

urlpatterns = [
   
    path('', home, name="home"),
    path('accounts/login/', register_and_login, name='register_and_login'),
    path('signout/', signout, name='signout'),
    path('dashboard/', user_dashboard, name='user_dashboard'),
    path('create_profile/', update_profile, name='update_profile'),
    
    path('instructor_dashboard/', instructor_dashboard, name='instructor_dashboard'),

    path('html_css/', html_css, name='html_css'),

    
    path('enroll/<slug:slug>/', enroll_course, name='enroll_course'),
    path('unenroll/<slug:slug>/', unenroll_course, name='unenroll_course'),

    path('course/<slug:slug>/', course_detail, name='course_detail'),


    path('save_user_codes/', save_user_codes, name='save_user_codes'),
    path('get_user_codes/', get_user_codes, name='get_user_codes'),


    path('projects/', projects, name='projects'),

    path('notes/', notes, name='make_notes'),
    path('ide/', ide, name='ide'),

    path('image-list/', image_list, name='image_list'),
    path('image/<int:image_id>/', view_image, name='view_image'),

    path('get-course-progress/<int:course_id>/', get_course_progress, name='get_course_progress'),

    # URL pattern for marking a lesson as completed
    path('mark-lesson-completed/', mark_lesson_completed, name='mark_lesson_completed'),
    path('connected_visitors/', connected_visitors, name='connected_visitors'),

] 

urlpatterns += staticfiles_urlpatterns()

instructors/models.py
from datetime import *
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from ckeditor.fields import RichTextField
# Create your models here.



class InstructorProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    biography = models.TextField()
    contact_info = models.CharField(max_length=200)
    is_creator = models.BooleanField(default=False)  # Indicates if the instructor can create courses

    def __str__(self):
        return self.user.username



class CourseCategories(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=300)
    slug = models.SlugField(unique=True, max_length=300, blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    
class Course(models.Model):
    category = models.ForeignKey(CourseCategories, on_delete=models.PROTECT)
    course_title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/course_images/')
    video_url = models.URLField(null=True)
    description = models.TextField()
    slug = models.SlugField(unique=True, blank=True)
    duration_in_days = models.IntegerField(default=100)
    instructor = models.ForeignKey(User, on_delete=models.PROTECT)  # Add this line to associate a course with an instructor
    is_published = models.BooleanField(default=False)
    
    @property
    def duration_in_weeks(self):
        return self.duration_in_days // 7

    class Meta:
        verbose_name_plural = 'Course'
        ordering = ('-course_title',)

    def get_absolute_url (self):
        return reverse('academy:course', args=[self.slug])

    def __str__(self):
        return self.course_title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.course_title)
        super().save(*args, **kwargs)


class Module(models.Model):
    id = models.AutoField(primary_key=True)
    module_title = models.CharField(max_length=200)
    description = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.PROTECT)


    def __str__(self):
        return self.module_title


class Lesson(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=500)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    module = models.ForeignKey(Module, default=None, null=True, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    content = RichTextField(null=True)
    created_at = models.DateTimeField(null=True)  # Make it nullable

    def __str__(self):
        return f"Lesson Created by {self.user.username}"

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        super().save(*args, **kwargs)



# assessments section 
class Assessment(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    course = models.ForeignKey(Course, default=None, null=True, on_delete=models.PROTECT)
    module = models.ForeignKey(Module, default=None, null=True, on_delete=models.PROTECT)
    lesson = models.ForeignKey(Lesson, default=None, null=True, on_delete=models.PROTECT)
    passing_score = models.PositiveIntegerField()
    is_taken = models.BooleanField(default=False)

    
    def __str__(self):
        return self.title
    

class Question(models.Model):
    text = models.TextField()
    assessment = models.ForeignKey('Assessment', on_delete=models.PROTECT)

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.CharField(max_length=500)
    question = models.ForeignKey('Question', on_delete=models.PROTECT)
    is_correct = models.BooleanField(default=False)


class AssessmentScore(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    assessment = models.ForeignKey(Assessment, on_delete=models.PROTECT)
    score = models.DecimalField(max_digits=5, decimal_places=2)  # Store the score as a decimal

    def __str__(self):
        return f"{self.user.username} - {self.assessment.title}"


class Resource(models.Model):
    resource_title = models.CharField(max_length=200)
    description = models.TextField()
    file = models.FileField(upload_to='resources/')  # Store files like videos, slides, etc.
    lesson = models.ForeignKey('Lesson', on_delete=models.PROTECT)


class Project(models.Model):
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    project_title = models.CharField(max_length=200)
    project_description = models.TextField(max_length=10000)
    # Other fields for Project

    class Meta:
        unique_together = ['course', 'project_title']  # Enforce uniqueness per course
    
    def __str__(self):
        return self.project_title

templates/courses/course_detail.html
{% extends 'dashboard.html' %}

{% load static %}
{% load custom_filters %}


{% block content %}

<div class="list-container">
  <h1 class="course-title">{{ course.course_title }}</h1>
  <iframe width="1250" height="650" src="{{ course.video_url }}" frameborder="0" allowfullscreen></iframe>
  <p class="course-description">{{ course.description|safe }}</p>

  {% if is_enrolled %}
    <h2 class="section-title">Modules and Lessons</h2>
    <div class="module-list">
      {% for module in modules %}
        <div class="module">
          <h6 class="module-title" id="module-{{ module.id }}">{{ module.module_title }}</h6>
          <div class="lesson-list hidden-lessons"> <!-- Added 'hidden-lessons' class -->
            {% for lesson in module.lesson_set.all %}
              <div class="lesson">
                <h6 class="lesson-title">{{ lesson.lesson_title }}</h6>
                <p class="lesson-content">{{ lesson.content|safe }}</p>
                <form class="lesson-completion-form" method="post" action="{% url 'academy:mark_lesson_completed' %}">
                  {% csrf_token %}
                  <input type="hidden" name="lesson_id" value="{{ lesson.id }}">
                  <button type="submit">Mark as Completed</button>
                </form>
              </div>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
  {% endif %}
  

  {% comment %} <div class="code_editor">
    <div class="code_editor_container">
        <div class="code_editor_wrapper">
            <div class="code_editor_segments" style="display: flex; flex-wrap: wrap;">

                <div class="code" style="margin: 5px;">
                    <h4>HTML</h4>
                    <div class="editorContainer editor_input" id="htmlEditor" style="height: 400px; width: 650px;"></div>
                </div>

                <div class="code" style="margin: 5px;">
                    <h4>CSS</h4>
                    <div class="editorContainer editor_input" id="cssEditor" style="height: 400px; width: 650px;"></div>
                </div>

                <div class="code" style="margin: 5px;">
                    <h4>JavaScript</h4>
                    <div class="editorContainer editor_input" id="jsEditor" style="height: 400px; width: 900px;"></div>
                </div>
                
            </div>
            <button class="run_btn" id="runButton"><i class='bx bx-play'></i>Run</button>
            <div class="code_editor_segments">
                <div class="output">
                    <h4>OutPut</h4>
                    <pre class="editor_output" id="output" style="width: 1300px; height: 700px;"></pre>
                </div>
                
            </div>
        </div>
    </div>
  </div> {% endcomment %}

  {% if is_enrolled %}
    <a href="{% url 'academy:course_detail' course.slug %}" ></a>
  {% else %}
    <form method="post" action="{% url 'academy:enroll_course' course.slug %}" class="enroll-form">
      {% csrf_token %}
      <button type="submit" class="btn btn-success enroll-btn">Enroll in Course</button>
    </form>
  {% endif %}

  {% if user == course.instructor %}
    <a href="{% url 'instructors:edit_course' slug=course.slug %}" class="btn btn-primary edit-course-btn">Edit Course</a>
    <form method="post" action="{% url 'instructors:delete_course' slug=course.slug %}" style="display: inline;">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger delete-course-btn" onclick="return confirm('Are you sure you want to delete this course?')">Delete Course</button>
    </form>
  {% endif %}
</div>

<style>
    /* Reset default margin and padding for all elements */
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    .list-container {
      background-color: #ffffff;
      border-radius: 5px;
      box-shadow: 0 5px 15px rgba(0, 0, 0, 0.35);
      position: relative;
      overflow: hidden;
      width: 1380px;
      padding: 10px;
      margin: 10px;
    }
    
    .course-title {
      font-size: 24px;
      margin-bottom: 20px;
    }
    
    .course-description {
      font-size: 14px;
      line-height: 20px;
      letter-spacing: 0.3px;
      margin-bottom: 20px;
    }
    
    .section-title {
      font-size: 18px;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    
    .module-title {
      font-size: 16px;
      margin-top: 10px;
      margin-bottom: 10px;
      cursor: pointer;
    }
    
    .lesson-title {
      font-size: 14px;
      margin-top: 10px;
      margin-bottom: 10px;
    }
    
    .lesson-content {
      font-size: 13px;
      line-height: 18px;
      margin-bottom: 20px;
    }
    
    .lesson-assessment-title {
      font-size: 16px;
      margin-top: 10px;
      margin-bottom: 10px;
    }
    
    .assessment-title {
      font-size: 14px;
      margin-top: 5px;
      margin-bottom: 5px;
    }
    
    .notes-title {
      font-size: 16px;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    
    .notes-link {
      font-size: 14px;
      text-decoration: underline;
      color: #007bff;
    }
    
    .assessment-ul {
      margin-top: 20px;
    }
    
    .assessment {
      font-size: 14px;
      margin-bottom: 10px;
    }
    
    .assessment-link {
      font-size: 14px;
      text-decoration: underline;
      color: #007bff;
    }
    
    .projects-link {
      font-size: 14px;
      text-decoration: underline;
      color: #007bff;
    }
    
    .enroll-form {
      margin-top: 20px;
    }
    
    .enroll-btn {
      background-color: #512da8;
      color: #fff;
      font-size: 12px;
      padding: 10px 45px;
      border: 1px solid transparent;
      border-radius: 8px;
      font-weight: 600;
      letter-spacing: 0.5px;
      text-transform: uppercase;
      cursor: pointer;
    }
    
    .edit-course-btn {
      background-color: #512da8;
      color: #fff;
      font-size: 12px;
      padding: 10px 20px;
      border: 1px solid transparent;
      border-radius: 8px;
      font-weight: 600;
      letter-spacing: 0.5px;
      text-transform: uppercase;
      cursor: pointer;
      margin-top: 10px;
    }
    
    .delete-course-btn {
      background-color: #ff0000;
      color: #fff;
      font-size: 12px;
      padding: 10px 20px;
      border: 1px solid transparent;
      border-radius: 8px;
      font-weight: 600;
      letter-spacing: 0.5px;
      text-transform: uppercase;
      cursor: pointer;
      margin-top: 10px;
    }
    
    /* Add more styles as needed */
    .hidden-lessons {
      display: none;
    }

  
</style>

<script>

 // <!-- JavaScript to toggle the visibility of lesson lists -->

    // Get all module title elements
    const moduleTitles = document.querySelectorAll('.module-title');

    // Add click event listeners to toggle the lesson list visibility
    moduleTitles.forEach(moduleTitle => {
      moduleTitle.addEventListener('click', () => {
        const lessonList = moduleTitle.nextElementSibling;
        lessonList.classList.toggle('hidden-lessons');
      });
    });


    // Use JavaScript to submit the form when the user clicks a button or performs an action
    document.getElementById('lesson-completion-form').addEventListener('submit', function (e) {
      e.preventDefault();
      fetch(this.action, {
        method: 'POST',
        body: new FormData(this),
      }).then(response => {
        if (response.ok) {
          // Handle success, e.g., update the UI to show the lesson as completed
          console.log('Lesson marked as completed');
        } else {
          // Handle error
          console.error('Error marking lesson as completed');
        }
      });
    });
</script>
{% endblock %}

templates/courses/course_list.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="content-container">
  <div class="categories">
    <h1>All Courses</h1>
    <h2>Categories</h2>
    <ul>
      <li><a href="{% url 'instructors:courses_by_category' %}">All</a></li>
      {% for category in categories %}
      <li><a href="{% url 'instructors:courses_by_category' %}?category={{ category.slug }}">{{ category.title }}</a></li>
      {% endfor %}
    </ul>
  </div>

  <div class="courses">
    {% if category_filter %}
    <h2>Courses in {{ category_filter.title }} Category</h2>
    {% endif %}

    <ul>
      {% for category, courses in courses_by_category.items %}
      {% if not category_filter or category_filter == category.slug %}
      <h3>{{ category }}</h3>
      <ul>
        {% for course in courses %}
        <li>
          <a href="{% url 'academy:course_detail' course.slug %}" class="course-link">{{ course.course_title }}</a>
          <p class="course-description">{{ course.description }}</p> <!-- Display course description -->
          {% if user.is_authenticated %}
            {% if course in user.student.enrolled_courses.all %}
              <em>Enrolled</em>
              <a href="{% url 'academy:course_detail' course.slug %}" class="btn btn-primary start-course-btn">Start Taking Course</a>
            {% else %}
              <form method="post" action="{% url 'academy:enroll_course' course.slug %}" class="enroll-form">
                {% csrf_token %}
                <button type="submit" class="btn btn-success enroll-btn">Enroll in Course</button>
              </form>
            {% endif %}
          {% else %}
            <a href="" class="btn btn-primary sign-in-btn">Sign in to Enroll</a>
          {% endif %}
        </li>
        {% endfor %}
      </ul>
      {% endif %}
      {% endfor %}
    </ul>
  </div>
</div>

<style>
  /* Apply these styles to your HTML */

  /* Main container styles */
  .content-container {
    display: flex;
    justify-content: space-between;
    padding: 20px;
    background-color: #f5f5f5;
    width: 1400px;
  }

  .categories {
    flex-basis: 25%;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 20px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .categories h2 {
    font-size: 18px;
    margin-bottom: 10px;
  }

  .categories ul {
    list-style: none;
    padding: 0;
  }

  .categories li {
    margin-bottom: 10px;
    border-radius: 3px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
    padding: 4px;
  }

  .categories a {
    text-decoration: none;
    color: #333;
    font-weight: bold;
  }

  .categories a:hover {
    color: #007bff;
  }

  .courses {
    flex-basis: 70%;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 20px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    
  }

  .courses h2 {
    font-size: 20px;
    margin-bottom: 15px;
  }

  .courses h3 {
    font-size: 16px;
    margin-top: 15px;
  }

  .courses ul {
    list-style: none;
    padding: 0;
  }

  .courses li {
    margin-bottom: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    padding: 1rem;
    border-radius: 5px;
  }

  .courses .course-link {
    text-decoration: none;
    color: black;
    font-weight: bold;
  }

  .courses .course-link:hover {
    text-decoration: underline;
  }

  .course-description {
    margin-top: 5px;
    color: #666;
  }
</style>
{% endblock %}